import { randomUUID } from "crypto";
import sharp from "sharp";

import { env } from "@/lib/env";
import { supabaseAdmin } from "@/lib/supabase/server";

import type {
  ImageSource,
  ImageSourcePref,
} from "@/lib/types";

const STORAGE_BUCKET = "post-images";

const GEMINI_IMAGE_MODEL =
  "gemini-3.1-flash-image";

const GEMINI_IMAGE_ENDPOINT =
  "https://generativelanguage.googleapis.com/v1beta/interactions";

const GEMINI_TIMEOUT_MS = 90_000;

const PEXELS_TIMEOUT_MS = 20_000;

// ============================================================
// FINAL IMAGE
// ============================================================

const FINAL_WIDTH = 1080;
const FINAL_HEIGHT = 1080;

// ============================================================
// SOURCE RESOLUTION
// ============================================================

export function resolveImageSource(
  pref: ImageSourcePref
): ImageSource {
  if (pref === "mixed") {
    return Math.random() < 0.5
      ? "ai"
      : "stock";
  }

  return pref;
}

// ============================================================
// GEMINI PROMPT
// ============================================================

const PHOTO_STYLE = [
  "photorealistic",
  "professional photography",
  "natural lighting",
  "realistic details",
  "high detail",
  "clean composition",
  "single scene",
  "single image",
  "no watermark",
  "no logo",
  "no collage",
  "no grid",
].join(", ");

/*
 * IMPORTANT:
 *
 * Gemini deliberately creates a CLEAN image without text.
 *
 * The Facebook headline is NOT generated by Gemini.
 * Sharp adds the headline afterwards.
 *
 * This prevents Gemini from producing misspelled,
 * missing, distorted, or random text.
 */
function buildGeminiPrompt(
  prompt: string,
  _title: string
): string {
  return [
    "Create a high-quality square social media photograph.",
    "",
    "VISUAL CONCEPT:",
    prompt.trim(),
    "",
    "IMPORTANT:",
    "- Create the image only.",
    "- Do NOT add any text, letters, words, captions, headlines, typography, signs, labels, logos, or watermarks.",
    "- Keep the image visually clean.",
    "- The final headline will be added separately after image generation.",
    "",
    "VISUAL STYLE:",
    PHOTO_STYLE,
    "",
    "COMPOSITION:",
    "- 1:1 square composition.",
    "- Designed for a Facebook mobile feed.",
    "- Strong visual hierarchy.",
    "- Main subject should remain visually dominant.",
    "- Professional viral social-media photography aesthetic.",
  ].join("\n");
}

// ============================================================
// PEXELS SEARCH QUERY
// ============================================================

function buildPexelsQuery(
  prompt: string
): string {
  const query =
    prompt
      .replace(
        /create|generate|image|photo|photograph|photorealistic|professional|high quality/gi,
        " "
      )
      .replace(
        /social media|square|natural lighting|realistic|high detail|clean composition/gi,
        " "
      )
      .replace(
        /no text|no watermark|no logo|no collage|no grid/gi,
        " "
      )
      .replace(
        /bold overlay text|overlay text|headline text|typography|font|contrast box/gi,
        " "
      )
      .replace(
        /[^a-zA-Z0-9À-ÿ\s-]/g,
        " "
      )
      .replace(
        /\s+/g,
        " "
      )
      .trim();

  const words =
    query
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 8);

  if (words.length === 0) {
    return "lifestyle";
  }

  return words.join(" ");
}

// ============================================================
// GEMINI IMAGE GENERATION
// ============================================================

async function fetchGeminiImageBytes(
  prompt: string,
  title: string
): Promise<Blob> {
  const apiKey =
    env.geminiApiKey;

  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is not configured"
    );
  }

  const cleanTitle =
    title.trim();

  if (!cleanTitle) {
    throw new Error(
      "Facebook headline is required before Gemini image generation."
    );
  }

  const finalPrompt =
    buildGeminiPrompt(
      prompt,
      cleanTitle
    );

  console.info(
    `[IMAGE] Gemini starting model=${GEMINI_IMAGE_MODEL}`
  );

  console.info(
    `[IMAGE] Gemini headline="${cleanTitle}"`
  );

  const requestBody = {
    model:
      GEMINI_IMAGE_MODEL,

    input: [
      {
        type: "text",
        text: finalPrompt,
      },
    ],

    response_format: {
      type: "image",
      mime_type: "image/jpeg",
      aspect_ratio: "1:1",
      image_size: "1K",
    },
  };

  const response =
    await fetch(
      GEMINI_IMAGE_ENDPOINT,
      {
        method: "POST",

        headers: {
          "Content-Type":
            "application/json",

          "x-goog-api-key":
            apiKey,
        },

        body:
          JSON.stringify(
            requestBody
          ),

        signal:
          AbortSignal.timeout(
            GEMINI_TIMEOUT_MS
          ),
      }
    );

  const body =
    await response.text();

  console.info(
    `[IMAGE] Gemini HTTP ${response.status}`
  );

  if (!response.ok) {
    console.error(
      "[IMAGE] Gemini API error:",
      body.slice(0, 1500)
    );

    throw new Error(
      `Gemini image API HTTP ${response.status}: ${body.slice(
        0,
        500
      )}`
    );
  }

  let data: any;

  try {
    data =
      JSON.parse(body);
  } catch {
    console.error(
      "[IMAGE] Gemini returned non-JSON:",
      body.slice(0, 1000)
    );

    throw new Error(
      "Gemini returned invalid JSON"
    );
  }

  // ==========================================================
  // PRIMARY: output_image.data
  // ==========================================================

  const outputImage =
    data?.output_image;

  if (
    outputImage &&
    typeof outputImage.data ===
      "string" &&
    outputImage.data.length > 0
  ) {
    const mimeType =
      typeof outputImage.mime_type ===
      "string"
        ? outputImage.mime_type
        : "image/jpeg";

    const bytes =
      Buffer.from(
        outputImage.data,
        "base64"
      );

    if (bytes.length === 0) {
      throw new Error(
        "Gemini returned empty image data"
      );
    }

    console.info(
      `[IMAGE] Gemini SUCCESS output_image bytes=${bytes.length}`
    );

    return new Blob(
      [bytes],
      {
        type: mimeType,
      }
    );
  }

  // ==========================================================
  // SECONDARY: steps[].content[]
  // ==========================================================

  const steps =
    Array.isArray(data?.steps)
      ? data.steps
      : [];

  for (const step of steps) {
    const content =
      Array.isArray(step?.content)
        ? step.content
        : [];

    for (const item of content) {
      if (
        item?.type === "image" &&
        typeof item?.data ===
          "string" &&
        item.data.length > 0
      ) {
        const mimeType =
          typeof item.mime_type ===
          "string"
            ? item.mime_type
            : "image/jpeg";

        const bytes =
          Buffer.from(
            item.data,
            "base64"
          );

        if (bytes.length === 0) {
          continue;
        }

        console.info(
          `[IMAGE] Gemini SUCCESS steps image bytes=${bytes.length}`
        );

        return new Blob(
          [bytes],
          {
            type: mimeType,
          }
        );
      }
    }
  }

  console.error(
    "[IMAGE] Gemini response contained no image."
  );

  console.error(
    "[IMAGE] Gemini response keys:",
    Object.keys(data ?? {})
  );

  throw new Error(
    "Gemini completed but returned no image data"
  );
}

// ============================================================
// PEXELS
// ============================================================

async function fetchStockImageBytes(
  prompt: string
): Promise<Blob> {
  const apiKey =
    env.pexelsApiKey;

  if (!apiKey) {
    throw new Error(
      "PEXELS_API_KEY is not configured"
    );
  }

  const query =
    buildPexelsQuery(
      prompt
    );

  console.info(
    `[IMAGE] Pexels query="${query}"`
  );

  const searchUrl =
    new URL(
      "https://api.pexels.com/v1/search"
    );

  searchUrl.searchParams.set(
    "query",
    query
  );

  searchUrl.searchParams.set(
    "orientation",
    "square"
  );

  searchUrl.searchParams.set(
    "size",
    "large"
  );

  searchUrl.searchParams.set(
    "per_page",
    "15"
  );

  const response =
    await fetch(
      searchUrl.toString(),
      {
        method: "GET",

        headers: {
          Authorization:
            apiKey,
        },

        signal:
          AbortSignal.timeout(
            PEXELS_TIMEOUT_MS
          ),
      }
    );

  const body =
    await response.text();

  console.info(
    `[IMAGE] Pexels HTTP ${response.status}`
  );

  if (!response.ok) {
    console.error(
      "[IMAGE] Pexels API error:",
      body.slice(0, 1000)
    );

    throw new Error(
      `Pexels HTTP ${response.status}: ${body.slice(
        0,
        500
      )}`
    );
  }

  let data: any;

  try {
    data =
      JSON.parse(body);
  } catch {
    throw new Error(
      "Pexels returned invalid JSON"
    );
  }

  const photos =
    Array.isArray(data?.photos)
      ? data.photos
      : [];

  if (photos.length === 0) {
    throw new Error(
      `Pexels returned no photos for query "${query}"`
    );
  }

  const validPhotos =
    photos.filter(
      (photo: any) =>
        typeof photo?.src?.large2x ===
          "string" ||
        typeof photo?.src?.large ===
          "string"
    );

  if (
    validPhotos.length === 0
  ) {
    throw new Error(
      "Pexels returned photos without usable URLs"
    );
  }

  const selected =
    validPhotos[
      Math.floor(
        Math.random() *
          validPhotos.length
      )
    ];

  const imageUrl =
    selected.src.large2x ??
    selected.src.large;

  console.info(
    "[IMAGE] Pexels downloading selected photo"
  );

  const imageResponse =
    await fetch(
      imageUrl,
      {
        method: "GET",

        signal:
          AbortSignal.timeout(
            PEXELS_TIMEOUT_MS
          ),
      }
    );

  if (!imageResponse.ok) {
    throw new Error(
      `Pexels image download HTTP ${imageResponse.status}`
    );
  }

  const blob =
    await imageResponse.blob();

  if (
    !blob.type ||
    !blob.type.startsWith(
      "image/"
    )
  ) {
    throw new Error(
      `Pexels returned invalid content type: ${blob.type}`
    );
  }

  if (blob.size === 0) {
    throw new Error(
      "Pexels returned an empty image"
    );
  }

  console.info(
    `[IMAGE] Pexels SUCCESS size=${blob.size} type=${blob.type}`
  );

  return blob;
}

// ============================================================
// SVG ESCAPE
// ============================================================

function escapeXml(
  value: string
): string {
  return value
    .replace(
      /&/g,
      "&amp;"
    )
    .replace(
      /</g,
      "&lt;"
    )
    .replace(
      />/g,
      "&gt;"
    )
    .replace(
      /"/g,
      "&quot;"
    )
    .replace(
      /'/g,
      "&apos;"
    );
}

// ============================================================
// REMOVE UNSAFE CHARACTERS
// ============================================================

function cleanHeadline(
  title: string
): string {
  return title
    .trim()
    .replace(
      /[\u0000-\u001F\u007F]/g,
      " "
    )
    .replace(
      /[\u{1F300}-\u{1FAFF}]/gu,
      ""
    )
    .replace(
      /[\u{2600}-\u{27BF}]/gu,
      ""
    )
    .replace(
      /\s+/g,
      " "
    )
    .trim();
}

// ============================================================
// HEADLINE WRAPPING
// ============================================================

function wrapHeadline(
  title: string,
  maxChars = 22
): string[] {
  const words =
    title
      .trim()
      .split(/\s+/)
      .filter(Boolean);

  if (words.length === 0) {
    return [];
  }

  const lines: string[] = [];

  let current = "";

  for (const word of words) {
    /*
     * Handle a single very long word.
     */
    if (
      word.length >
        maxChars &&
      !current
    ) {
      lines.push(
        word.slice(
          0,
          maxChars
        )
      );

      current =
        word.slice(
          maxChars
        );

      continue;
    }

    const candidate =
      current
        ? `${current} ${word}`
        : word;

    if (
      candidate.length <=
      maxChars
    ) {
      current =
        candidate;
    } else {
      if (current) {
        lines.push(
          current
        );
      }

      current =
        word;
    }
  }

  if (current) {
    lines.push(
      current
    );
  }

  /*
   * Maximum three lines.
   */
  if (lines.length <= 3) {
    return lines;
  }

  const first =
    lines[0];

  const second =
    lines[1];

  const remaining =
    lines
      .slice(2)
      .join(" ");

  return [
    first,
    second,
    remaining,
  ];
}

// ============================================================
// HEADLINE SVG
// ============================================================

function createHeadlineSvg(
  title: string
): Buffer {
  const cleanTitle =
    cleanHeadline(
      title
    );

  if (!cleanTitle) {
    throw new Error(
      "Headline title is empty after cleaning."
    );
  }

  const lines =
    wrapHeadline(
      cleanTitle,
      22
    );

  if (lines.length === 0) {
    throw new Error(
      "Unable to create headline overlay."
    );
  }

  const fontSize =
    lines.length === 1
      ? 96
      : lines.length === 2
        ? 82
        : 68;

  const lineHeight =
    fontSize + 18;

  /*
   * Put headline near the bottom,
   * with enough space from the edge.
   */
  const totalTextHeight =
    lines.length *
    lineHeight;

  const firstTextY =
    FINAL_HEIGHT -
    totalTextHeight -
    75;

  /*
   * Create EACH text line separately.
   *
   * This is more reliable with Sharp/libvips
   * than relying on nested <tspan> rendering.
   */
  const textElements =
    lines
      .map(
        (
          line,
          index
        ) => {
          const y =
            firstTextY +
            index *
              lineHeight;

          const safeText =
            escapeXml(
              line.toUpperCase()
            );

          return `
    <text
      x="540"
      y="${y}"
      text-anchor="middle"
      dominant-baseline="alphabetic"
      font-family="DejaVu Sans, Arial, sans-serif"
      font-size="${fontSize}px"
      font-weight="900"
      fill="#FFFFFF"
      stroke="#000000"
      stroke-width="10"
      stroke-linejoin="round"
      paint-order="stroke"
    >${safeText}</text>`;
        }
      )
      .join("\n");

  /*
   * No black rectangle.
   *
   * The headline uses:
   * - white fill
   * - thick black outline
   * - strong shadow
   *
   * This keeps the original photograph visible.
   */
  const svg = `
<svg
  width="${FINAL_WIDTH}"
  height="${FINAL_HEIGHT}"
  viewBox="0 0 ${FINAL_WIDTH} ${FINAL_HEIGHT}"
  xmlns="http://www.w3.org/2000/svg"
>
  <defs>
    <filter
      id="headlineShadow"
      x="-30%"
      y="-30%"
      width="160%"
      height="160%"
    >
      <feDropShadow
        dx="0"
        dy="6"
        stdDeviation="5"
        flood-color="#000000"
        flood-opacity="0.9"
      />
    </filter>
  </defs>

  <g filter="url(#headlineShadow)">
    ${textElements}
  </g>
</svg>
`;

  return Buffer.from(
    svg,
    "utf8"
  );
}

// ============================================================
// APPLY HEADLINE OVERLAY
// ============================================================

async function applyHeadlineOverlay(
  blob: Blob,
  title: string
): Promise<Blob> {
  const cleanTitle =
    cleanHeadline(
      title
    );

  /*
   * CRITICAL:
   *
   * Never silently return the original image.
   *
   * If title is missing, generation FAILS.
   */
  if (!cleanTitle) {
    throw new Error(
      "Cannot generate final image: Facebook headline/title is empty."
    );
  }

  console.info(
    `[IMAGE] REQUIRED HEADLINE="${cleanTitle}"`
  );

  console.info(
    `[IMAGE] OVERLAY START title="${cleanTitle}"`
  );

  const inputBuffer =
    Buffer.from(
      await blob.arrayBuffer()
    );

  if (
    inputBuffer.length === 0
  ) {
    throw new Error(
      "Cannot apply headline: source image is empty."
    );
  }

  /*
   * First normalize the source image.
   */
  const baseImage =
    await sharp(
      inputBuffer
    )
      .resize(
        FINAL_WIDTH,
        FINAL_HEIGHT,
        {
          fit: "cover",
          position: "centre",
        }
      )
      .jpeg({
        quality: 92,
        mozjpeg: true,
      })
      .toBuffer();

  if (
    baseImage.length === 0
  ) {
    throw new Error(
      "Base image processing produced empty output."
    );
  }

  const svgOverlay =
    createHeadlineSvg(
      cleanTitle
    );

  /*
   * Composite the headline.
   */
  const outputBuffer =
    await sharp(
      baseImage
    )
      .composite([
        {
          input:
            svgOverlay,

          top: 0,

          left: 0,
        },
      ])
      .jpeg({
        quality: 92,
        mozjpeg: true,
      })
      .toBuffer();

  if (
    outputBuffer.length === 0
  ) {
    throw new Error(
      "Headline overlay produced an empty image."
    );
  }

  /*
   * VERIFY FINAL IMAGE.
   */
  const metadata =
    await sharp(
      outputBuffer
    ).metadata();

  if (
    !metadata.width ||
    !metadata.height
  ) {
    throw new Error(
      "Headline overlay verification failed: invalid final image."
    );
  }

  console.info(
    `[IMAGE] OVERLAY SUCCESS title="${cleanTitle}" width=${metadata.width} height=${metadata.height} bytes=${outputBuffer.length}`
  );

  /*
   * IMPORTANT:
   *
   * Only this final image is returned.
   * The original base image is never uploaded.
   */
  return new Blob(
    [outputBuffer],
    {
      type: "image/jpeg",
    }
  );
}

// ============================================================
// PUBLIC GENERATOR
// ============================================================

export async function generateImage(
  prompt: string,
  pref: ImageSourcePref,
  title: string
): Promise<{
  url: string;
  source: ImageSource;
}> {
  const cleanPrompt =
    prompt.trim();

  const cleanTitle =
    cleanHeadline(
      title
    );

  if (!cleanPrompt) {
    throw new Error(
      "Image prompt is required."
    );
  }

  /*
   * CRITICAL:
   *
   * Title is mandatory.
   */
  if (!cleanTitle) {
    throw new Error(
      "Facebook headline/title is required for image generation."
    );
  }

  const source =
    resolveImageSource(
      pref
    );

  console.info(
    `[IMAGE] REQUESTED SOURCE=${source}`
  );

  console.info(
    `[IMAGE] REQUIRED HEADLINE="${cleanTitle}"`
  );

  // ==========================================================
  // AI SOURCE
  // Gemini -> Sharp -> upload
  // Pexels fallback -> Sharp -> upload
  // ==========================================================

  if (
    source === "ai"
  ) {
    try {
      const baseBlob =
        await fetchGeminiImageBytes(
          cleanPrompt,
          cleanTitle
        );

      /*
       * NEVER upload Gemini base image directly.
       */
      const finalBlob =
        await applyHeadlineOverlay(
          baseBlob,
          cleanTitle
        );

      return upload(
        finalBlob,
        "ai"
      );
    } catch (geminiError) {
      const message =
        geminiError instanceof Error
          ? geminiError.message
          : String(geminiError);

      console.error(
        `[IMAGE] Gemini FAILED: ${message}`
      );

      try {
        const baseBlob =
          await fetchStockImageBytes(
            cleanPrompt
          );

        /*
         * Pexels fallback ALSO receives
         * the mandatory Sharp headline.
         */
        const finalBlob =
          await applyHeadlineOverlay(
            baseBlob,
            cleanTitle
          );

        return upload(
          finalBlob,
          "stock"
        );
      } catch (pexelsError) {
        const message2 =
          pexelsError instanceof Error
            ? pexelsError.message
            : String(pexelsError);

        console.error(
          `[IMAGE] Pexels FALLBACK FAILED: ${message2}`
        );

        throw new Error(
          `Image generation failed. Gemini: ${message}. Pexels: ${message2}`
        );
      }
    }
  }

  // ==========================================================
  // STOCK SOURCE
  // Pexels -> Sharp -> upload
  // Gemini fallback -> Sharp -> upload
  // ==========================================================

  try {
    const baseBlob =
      await fetchStockImageBytes(
        cleanPrompt
      );

    const finalBlob =
      await applyHeadlineOverlay(
        baseBlob,
        cleanTitle
      );

    return upload(
      finalBlob,
      "stock"
    );
  } catch (pexelsError) {
    const message =
      pexelsError instanceof Error
        ? pexelsError.message
        : String(pexelsError);

    console.error(
      `[IMAGE] Pexels FAILED: ${message}`
    );

    try {
      const baseBlob =
        await fetchGeminiImageBytes(
          cleanPrompt,
          cleanTitle
        );

      const finalBlob =
        await applyHeadlineOverlay(
          baseBlob,
          cleanTitle
        );

      return upload(
        finalBlob,
        "ai"
      );
    } catch (geminiError) {
      const message2 =
        geminiError instanceof Error
          ? geminiError.message
          : String(geminiError);

      console.error(
        `[IMAGE] Gemini FALLBACK FAILED: ${message2}`
      );

      throw new Error(
        `Image generation failed. Pexels: ${message}. Gemini: ${message2}`
      );
    }
  }
}

// ============================================================
// SUPABASE STORAGE
// ============================================================

async function upload(
  blob: Blob,
  source: ImageSource
): Promise<{
  url: string;
  source: ImageSource;
}> {
  const db =
    supabaseAdmin();

  /*
   * generateImage() always returns JPEG after Sharp.
   */
  const extension =
    "jpg";

  const date =
    new Date()
      .toISOString()
      .slice(0, 10);

  const path =
    `${date}/${randomUUID()}.${extension}`;

  const bytes =
    new Uint8Array(
      await blob.arrayBuffer()
    );

  if (bytes.length === 0) {
    throw new Error(
      "Cannot upload empty image."
    );
  }

  console.info(
    `[IMAGE] SUPABASE UPLOAD source=${source} path=${path} size=${bytes.length}`
  );

  const {
    error,
  } =
    await db.storage
      .from(
        STORAGE_BUCKET
      )
      .upload(
        path,
        bytes,
        {
          contentType:
            "image/jpeg",

          upsert: false,
        }
      );

  if (error) {
    throw new Error(
      `Supabase Storage upload failed: ${error.message}`
    );
  }

  const {
    data,
  } =
    db.storage
      .from(
        STORAGE_BUCKET
      )
      .getPublicUrl(
        path
      );

  if (
    !data?.publicUrl
  ) {
    throw new Error(
      "Supabase did not return public image URL."
    );
  }

  console.info(
    `[IMAGE] SUPABASE UPLOAD SUCCESS source=${source} url=${data.publicUrl}`
  );

  return {
    url:
      data.publicUrl,

    source,
  };
}
